noobclang: allow invocation as noobclang++ to support C++ linking

diff --git a/noobclang b/noobclang
--- a/noobclang
+++ b/noobclang
@@ -13,6 +13,18 @@ fi
 
 NOOB_BUILD_DIR=$(realpath "$NOOB_BUILD_DIR")
 
+# Figure out whether this script was invoked as "noobclang" or "noobclang++"
+invocation_name=$(basename "$0")
+clang_command="${invocation_name#noob}-15"
+
+# Check if clang_command is empty or invalid
+if [[ -z "$clang_command" ]]; then
+    echo "Error: Script should be invoked with a 'noob' prefix, followed by a valid clang command (e.g., 'noobclang', 'noobclang++')."
+    exit 1
+fi
+
+echo "Using clang command: $clang_command"
+
 # Separate source files (ending in .o) and other arguments
 source_files=()
 other_args=()
@@ -29,11 +41,11 @@ echo "Source files: ${source_files[@]}"
 echo "Other args: ${other_args[@]}"
 
 # First invocation: create the instrumented bitcode with only source files and LTO options
-clang-15 "$@" -flto -fuse-ld=/usr/bin/ld.lld-15 -Xclang -disable-O0-optnone \
+$clang_command "$@" -flto -fuse-ld=/usr/bin/ld.lld-15 -Xclang -disable-O0-optnone \
         -Xlinker --load-pass-plugin=${NOOB_BUILD_DIR}/llvm-plugin/libllvmnoob.so -Wl,-plugin-opt=no-opaque-pointers \
         -Wl,-save-temps -o noob.tmp -r
 
 # Second invocation: link with libraries and generated linker script, omitting source files
-clang-15 "${other_args[@]}" -fuse-ld=/usr/bin/ld.lld-15 noob.tmp.0.5.precodegen.bc \
+$clang_command "${other_args[@]}" -fuse-ld=/usr/bin/ld.lld-15 noob.tmp.0.5.precodegen.bc \
         -Wl,-rpath=${NOOB_BUILD_DIR}/allocator/ ${NOOB_BUILD_DIR}/allocator/libnooballoc.so \
         -T noob_linker_script.ld -mcmodel=large -no-pie
