noobclang: support `nooballocclang`

diff --git a/templates/noobclang b/templates/noobclang
--- a/templates/noobclang
+++ b/templates/noobclang
@@ -6,11 +6,16 @@ set -e
 
 # Figure out whether this script was invoked as "noobclang" or "noobclang++"
 invocation_name=$(basename "$0")
-clang_command="${invocation_name#noob}-15"
+
+if [[ "$invocation_name" == *"++" ]]; then
+    clang_command="clang++-15"
+else
+    clang_command="clang-15"
+fi
 
 # Check if clang_command is empty or invalid
 if [[ -z "$clang_command" ]]; then
-    >&2 echo "Error: Script should be invoked with a 'noob' prefix, followed by a valid clang command (e.g., 'noobclang', 'noobclang++')."
+    >&2 echo "Error: could not find command: $clang_command"
     exit 1
 fi
 
@@ -18,6 +23,6 @@ set -x
 
 # Actual invocation here
 $clang_command "$@" -flto -fuse-ld=/usr/bin/ld.lld-15 -Xclang -disable-O0-optnone -Xclang -no-opaque-pointers \
-        -Xlinker --load-pass-plugin=@CMAKE_BINARY_DIR@/llvm-plugin/libllvmnoob.so -Wl,-plugin-opt=no-opaque-pointers \
+        @NOOB_PLUGIN_FLAGS@ \
         -Wl,-rpath=@CMAKE_BINARY_DIR@/allocator/ @CMAKE_BINARY_DIR@/allocator/libnooballoc.so \
         -Wl,-dynamic-linker,@CMAKE_BINARY_DIR@/n00bloader/n00bloader
